name: hyp3-itslive-metadata
channels:
  - conda-forge
dependencies:
  - python>=3.11
  - pip
  # For packaging, and testing
  - setuptools_scm
  - pytest
  - pytest-console-scripts
  - pytest-cov
  - ciso8601
  - neovim
  - zarr<=3.0.0a
  - unzip
  # For running
  - boto3
  - hyp3lib>=3,<4
  - s3fs>=2025.1.0
  - pip:
      - -r requirements-static.txt
